name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: dub test
    strategy:
      matrix:
        dc: [dmd-latest, ldc-latest]
    runs-on:
      ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - uses: jcbhmr/setup-wasm-tools@v2
      - run: dub test
